version: '3.8'

services:
  db:
    build: ./init-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospedaje_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
      - ./init-db/my.cnf:/etc/mysql/my.cnf

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user:password@db/hospedaje_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
    depends_on:
      - backend